name: FlyNoKill
main: me.gomeow.flynokill.flynokill
version: 1.2
description: If a player is flying and is in survival, they cannot harm entities.

author: gomeow

permissions:
  flynokill.*:
    description: Gives all FlyNoKill permissions.
    children:
      flynokill.bypass:
        description: Allows players who are in survival and are flying to attack.
        default: op